# Generated by Django 3.0.5 on 2022-03-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratorie',
        ),
    ]
