# Generated by Django 3.0.5 on 2022-03-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0003_laboratorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorie',
            name='supervisor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Supervisor'),
        ),
    ]
