# Generated by Django 3.0.5 on 2022-04-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0004_laboratorie_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorie',
            name='data_show',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=1, max_length=50, verbose_name='Data Show'),
            preserve_default=False,
        ),
    ]
