# Generated by Django 3.0.5 on 2022-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0005_laboratorie_data_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorie',
            name='data_show',
            field=models.BooleanField(default=True, verbose_name='Data Show'),
        ),
    ]
