# Generated by Django 3.0.5 on 2022-03-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=50, verbose_name='Day')),
            ],
        ),
        migrations.CreateModel(
            name='Tiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end', models.TimeField(auto_created=True, verbose_name='end at')),
                ('start', models.TimeField(verbose_name='start at')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch')),
                ('level', models.CharField(max_length=200, verbose_name='Level')),
                ('subject_name', models.CharField(max_length=200, verbose_name='Subject Name')),
                ('time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lectures', to='halls.Tiem')),
            ],
        ),
        migrations.CreateModel(
            name='hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('seats', models.IntegerField(null=True, verbose_name='Seats')),
                ('days', models.ManyToManyField(to='halls.Day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='lectures',
            field=models.ManyToManyField(null=True, related_name='a', to='halls.Lecture'),
        ),
    ]
