# Generated by Django 3.0.5 on 2022-03-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_day_2_hall2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_2',
            name='end_lect_one',
            field=models.TimeField(auto_created=True, null=True, verbose_name='lecture one end at'),
        ),
        migrations.AlterField(
            model_name='day_2',
            name='end_lect_tow',
            field=models.TimeField(auto_created=True, null=True, verbose_name='lecture tow end at'),
        ),
        migrations.AlterField(
            model_name='day_2',
            name='lecture_one',
            field=models.CharField(max_length=50, null=True, verbose_name='lecture one'),
        ),
        migrations.AlterField(
            model_name='day_2',
            name='lecture_tow',
            field=models.CharField(max_length=50, null=True, verbose_name='lecture tow'),
        ),
        migrations.AlterField(
            model_name='day_2',
            name='start_lect_one',
            field=models.TimeField(null=True, verbose_name='lecture one start at'),
        ),
        migrations.AlterField(
            model_name='day_2',
            name='start_lect_tow',
            field=models.TimeField(null=True, verbose_name='lecture toe start at'),
        ),
    ]
