# Generated by Django 3.0.5 on 2022-03-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_auto_20220301_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall2',
            name='supervisor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Seats'),
        ),
    ]
