# Generated by Django 3.0.5 on 2022-03-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0008_auto_20220301_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall2',
            name='days',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='time',
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name': 'Hall', 'verbose_name_plural': 'Halls'},
        ),
        migrations.RemoveField(
            model_name='day',
            name='lectures',
        ),
        migrations.AddField(
            model_name='day',
            name='end_lect_one',
            field=models.TimeField(auto_created=True, null=True, verbose_name='End at'),
        ),
        migrations.AddField(
            model_name='day',
            name='end_lect_three',
            field=models.TimeField(auto_created=True, null=True, verbose_name='End at'),
        ),
        migrations.AddField(
            model_name='day',
            name='end_lect_tow',
            field=models.TimeField(auto_created=True, null=True, verbose_name='End at'),
        ),
        migrations.AddField(
            model_name='day',
            name='lect_one_given_by',
            field=models.CharField(max_length=50, null=True, verbose_name='given by'),
        ),
        migrations.AddField(
            model_name='day',
            name='lect_three_given_by',
            field=models.CharField(max_length=50, null=True, verbose_name='given by'),
        ),
        migrations.AddField(
            model_name='day',
            name='lect_tow_given_by',
            field=models.CharField(max_length=50, null=True, verbose_name='given by'),
        ),
        migrations.AddField(
            model_name='day',
            name='lecture_one',
            field=models.CharField(max_length=50, null=True, verbose_name='lecture one'),
        ),
        migrations.AddField(
            model_name='day',
            name='lecture_three',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lecture three'),
        ),
        migrations.AddField(
            model_name='day',
            name='lecture_tow',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lecture tow'),
        ),
        migrations.AddField(
            model_name='day',
            name='start_lect_one',
            field=models.TimeField(null=True, verbose_name='Start at'),
        ),
        migrations.AddField(
            model_name='day',
            name='start_lect_three',
            field=models.TimeField(null=True, verbose_name='Start at'),
        ),
        migrations.AddField(
            model_name='day',
            name='start_lect_tow',
            field=models.TimeField(null=True, verbose_name='Start at'),
        ),
        migrations.AddField(
            model_name='hall',
            name='supervisor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='supervisor'),
        ),
        migrations.DeleteModel(
            name='Day_2',
        ),
        migrations.DeleteModel(
            name='Hall2',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Tiem',
        ),
    ]
