# Generated by Django 3.0.5 on 2022-03-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0010_auto_20220301_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='end_lect_one',
            field=models.TimeField(auto_created=True, blank=True, null=True, verbose_name='End at'),
        ),
        migrations.AlterField(
            model_name='day',
            name='start_lect_one',
            field=models.TimeField(blank=True, null=True, verbose_name='Start at'),
        ),
    ]
