# Generated by Django 3.0.5 on 2022-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0012_auto_20220302_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='start_lect_three',
            field=models.TimeField(blank=True, null=True, verbose_name='Start at'),
        ),
    ]
