# Generated by Django 3.0.5 on 2022-04-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0016_hall_data_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='data_show',
            field=models.BooleanField(default=True, verbose_name='Data Show'),
        ),
    ]
