# Generated by Django 3.0.5 on 2022-05-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0018_auto_20220520_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='level_and_branch',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lvel/Branch'),
        ),
    ]
