# Generated by Django 3.0.5 on 2022-05-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0019_day_level_and_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='level_and_branch',
        ),
        migrations.AddField(
            model_name='day',
            name='level_and_branch_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch/Level'),
        ),
        migrations.AddField(
            model_name='day',
            name='level_and_branch_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch/Level'),
        ),
        migrations.AddField(
            model_name='day',
            name='level_and_branch_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Branch/Level'),
        ),
    ]
